### ISSUE TITLE
Importing other robot arms to the trainingsystem

### ISSUE THREAD

**Issue by hoho2312** [SamuelSchmidgall/SurgicalGym#2]
Thank you very much for providing such fascinating platform for parallel training with surgical robot! However, I see that the platform now mostly provides robot arms configs from the DaVinci system. Would there be any possible way for users to import / create their custom robot arms (e.g. like UR or Franka etc..)? I see that there are some .usd and their corresponding .py files, should we also like having our own .usd and .py for importing other robot arms?

**Comment by SamuelSchmidgall** [comment]
Of course, I am glad you are enjoying it. Yes, you are able to import your own arms. You need to use the IsaacGym conversion script and just plug it into where the other USDs are inserted. You will also have to write some code for initializing the joints, etc, but otherwise should follow the same format.

See the following link for conversion: https://docs.omniverse.nvidia.com/isaacsim/latest/features/external_communication/ext_omni_exporter_urdf.html
